// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     // ignore: missing_enum_constant_in_switch
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//     }
//
//     throw UnsupportedError(
//       'DefaultFirebaseOptions are not supported for this platform.',
//     );
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDNQN3CqKN52imrBElkpA2cd0bPt6JzmQw',
//     appId: '1:623652127430:android:90cd8fdf32703d36118dc7',
//     messagingSenderId: '623652127430',
//     projectId: 'academia-app-8ac31',
//     storageBucket: 'academia-app-8ac31.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBWPDzytSQi4U9sUcVOcSjHGqlTApK6D70',
//     appId: '1:623652127430:ios:07d0cb29acbc5574118dc7',
//     messagingSenderId: '623652127430',
//     projectId: 'academia-app-8ac31',
//     storageBucket: 'academia-app-8ac31.appspot.com',
//     androidClientId: '623652127430-pciivn0avpp58en8lc30n53bf2bnbctr.apps.googleusercontent.com',
//     iosClientId: '623652127430-4lv8t2hjtud09p3adfgkue1rotjgvmqt.apps.googleusercontent.com',
//     iosBundleId: 'exit',
//   );
// }
